    bookBoxApp.controller("anonymousCategoryPageCtrl",     
                          ['$scope',
                           '$location',
                           'anonymousCategoryService',
                           'userManagementService',
                           'anonymousBookService',
                           function($scope,$location,anonymousCategoryService,userManagementService,anonymousBookService){
                               $scope.searchText;
                               $scope.selectedItem;
                               $scope.selectedType='None';
                               $scope.categoryDetails={name:'',books:[]};
                               $scope.currentUser="";
                               $scope.currentUserId=0;
                               $scope.init=function(){debugger;
                                    var userInfo= userManagementService.getCurrentUser();                  
                                   $scope.categoryDetails=anonymousCategoryService.getCategoryDetails();
                                  if(userInfo){
                                      $scope.currentUser=userInfo.user.name;
                                      $scope.currentUserId=userInfo.user.userId;
                                  }                  
                               }
                               $scope.init();
                               $scope.goToAnonymousBookPage=function(book){
                                       anonymousBookService.getReviewCountFromServer(book.bookId).
                                       success(function(count){
                                       anonymousBookService.setBookToDisplay(book);
                                       anonymousBookService.setReviewCount(count);          
                                       $location.path("/bookDetails");
                                       }).error(function(error){alert("Error!")});
                               }
         
    }])