    bookBoxApp.config(function($routeProvider, $locationProvider){

        $routeProvider
        .when("/", {
            templateUrl: "/BookBox/BookBoxUX/app/components/anonymousHomePage/anonymousHomePage.html",
            controller:"anonymousHomeCtrl"
        })
        .when("/bookDetails",{
            templateUrl:"/BookBox/BookBoxUX/app/components/anonymousBookPage/anonymousBookPage.html",
            controller:"anonymousBookPageCtrl"
        })
        .when("/categories",{
            templateUrl:"/BookBox/BookBoxUX/app/components/anonymousCategoryPage/anonymousCategoryPage.html",
            controller:"anonymousCategoryPageCtrl"
        })
        .when("/login",{
            templateUrl:"/BookBox/BookBoxUX/app/components/loginPage/loginPage.html",
            controller:"loginPageCtrl"
        })
        .when("/loggedin",{
            templateUrl:"/BookBox/BookBoxUX/app/components/loggedInHomePage/loggedInHomePage.html",
            controller:"loggedInHomePageCtrl"
        })
        .when("/signup",{
            templateUrl:"/BookBox/BookBoxUX/app/components/signUpPage/signUpPage.html",
            controller:"signUpCtrl"
        })
        .when("/categoryListing",{
            templateUrl:"/BookBox/BookBoxUX/app/components/categoryListingPage/categoryListingPage.html",
            controller:"categoryListingCtrl"
        })
        .when("/playlists",{
            templateUrl:"/BookBox/BookBoxUX/app/components/playlists/playlists.html",
            controller:"playlistsCtrl"
        })
        .when("/history",{
            templateUrl:"/BookBox/BookBoxUX/app/components/history/history.html",
            controller:"historyCtrl"
        })
        .when("/settings",{
            templateUrl:"/BookBox/BookBoxUX/app/components/settings/settings.html",
            controller:"settingsCtrl"
        })
        .when("/editUser",{
            templateUrl:"/BookBox/BookBoxUX/app/components/editUser/editUser.html",
            controller:"editUserCtrl"
        })
        .when("/bookReader",{
            templateUrl:"/BookBox/BookBoxUX/app/components/bookReader/bookReader.html",
            controller:"bookReaderCtrl"
        });
    })